name: Automated_Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

     - name: Set up ChromeDriver
      run: |
        CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
        wget -q -O chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver.zip
        chmod +x chromedriver
        echo "PATH=\$HOME:\$PATH" >> $GITHUB_ENV

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

        

    - name: Install Maven
      run: sudo apt-get install maven -y

    - name: Build with Maven
      run: mvn clean install -DskipTests=true

    - name: Run Tests
      run: mvn test

    - name: Notify on Failure
      if: failure()
      run: echo "Tests failed! Notify someone."

    - name: Notify on Success
      if: success()
      run: echo "Tests passed! Good job."

    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: target/surefire-reports

   


